### ISSUE TITLE
ldap connect problem

### ISSUE THREAD

**Issue by canlar** [dalibo/ldap2pg#124]
I have Redhat 7 with python 2.7.5 an ldap2pg 3.3

``` console
-bash-4.2$ python -V
Python 2.7.5
-bash-4.2$

-bash-4.2$ ldap2pg -c ldap2pg.minimal.yml -V
ldap2pg 3.3

-bash-4.2$ ldap2pg -c ldap2pg.minimal.yml
Starting ldap2pg 3.3.
Using /var/lib/pgsql/ldap2pg.minimal.yml.
Failed to connect to LDAP: {'info': '8009030C: LdapErr: DSID-0C090535, comment: AcceptSecurityContext error, data 52e, v1772', 'desc': 'Invalid credentials'}

-bash-4.2$ DEBUG=1 ldap2pg -c ldap2pg.minimal.yml
[ldap2pg.script      DEBUG] Debug mode enabled.
[ldap2pg.config      DEBUG] Processing CLI arguments.
[ldap2pg.config       INFO] Starting ldap2pg 3.3.
[ldap2pg.config      DEBUG] Trying ldap2pg.minimal.yml.
[ldap2pg.config       INFO] Using /var/lib/pgsql/ldap2pg.minimal.yml.
[ldap2pg.config      DEBUG] Read color from YAML.
[ldap2pg.config      DEBUG] Read dry from YAML.
[ldap2pg.config      DEBUG] Read verbose from DEBUG.
[ldap2pg.config      DEBUG] Read ldap:uri from YAML.
[ldap2pg.config      DEBUG] Read ldap:password from YAML.
[ldap2pg.config      DEBUG] Read postgres:dsn from YAML.
[ldap2pg.config      DEBUG] Read sync_map from YAML.
[ldap2pg.config      DEBUG] Configuration loaded.
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'/etc/ldap/ldap.conf'
[ldap2pg.ldap        DEBUG] Found rcfile /var/lib/pgsql/ldaprc.
[ldap2pg.ldap        DEBUG] Read BINDDN from /var/lib/pgsql/ldaprc.
[ldap2pg.ldap        DEBUG] Read BASE from /var/lib/pgsql/ldaprc.
[ldap2pg.ldap        DEBUG] Unknown option BASE
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'/var/lib/pgsql/.ldaprc'
[ldap2pg.ldap        DEBUG] Found rcfile ldaprc.
[ldap2pg.ldap        DEBUG] Read BINDDN from ldaprc.
[ldap2pg.ldap        DEBUG] Read BASE from ldaprc.
[ldap2pg.ldap        DEBUG] Unknown option BASE
[ldap2pg.ldap        DEBUG] Connecting to LDAP server ldap://ldap.company.cnb:389.
[ldap2pg.ldap        DEBUG] Trying simple bind.
[ldap2pg.script   CRITICAL] Failed to connect to LDAP: {'info': '80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580', 'desc': 'Invalid credentials'}

-bash-4.2$ cat ldap2pg.minimal.yml
color: yes
dry: yes
ldap:
  uri: ldap://de.company.cnb:389
  password: "XXXXXXX"

postgres:
  dsn: postgres://postgres/xxxxx@pgtest2.de.xxxx.cnb:5432/
```

If i use user and Passwort i get this error: 

``` console
[ldap2pg.ldap        DEBUG] Trying SASL DIGEST-MD5 auth.
[ldap2pg.script   CRITICAL] Failed to connect to LDAP: {'info': '8009030C: LdapErr: DSID-0C09056D, comment: AcceptSecurityContext error, data 52e, v2580', 'desc': 'Invalid credentials'}
```

With ldapsearch command give user and password with option -x i get not error.
How can i config ldap connection to use user and password with simple bind ?

**Comment by bersace** [comment]
Hi @canlar thanks for reporting this !

**Comment by bersace** [comment]
@canlar can you show me a `ldapsearch` example without password ?

**Comment by bersace** [comment]
That would be nice if `ldap2pg` logs a `ldapwhoami` commands to test how it is authenticating with LDAP.

**Comment by bersace** [comment]
I see that `ldap2pg` reads twice `ldaprc`, that's not a bug, but could be improved.

```
> [ldap2pg.ldap        DEBUG] Found rcfile /var/lib/pgsql/ldaprc.
> [ldap2pg.ldap        DEBUG] Found rcfile ldaprc.
```

**Comment by canlar** [comment]
[ldap2pg.manager      INFO] Querying LDAP cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=xxxx,DC=cnb...
[ldap2pg.ldap        DEBUG] Doing: ldapsearch -x -b cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=xxxx,DC=cnb -s sub '(objectClass=groupOfNames)' member
[ldap2pg.script   CRITICAL] Failed to query LDAP: {'info': '000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580', 'desc': 'Operations error'}.

execute ldapsearch in commandline  with username and type password  i can i get members but if i write this things in config file the ldap2pg switch to SASL DIGEST-MD5 and this is not configured or supported on my Server.
ldapsearch -x -H ldap://xxxx.cnb:389 -L -D 'userxxx' -W -b 'CN=manager,OU=Groups,OU=IAM,OU=_DomainOperations,DC=company,DC=cnb' member

**Comment by bersace** [comment]
@canlar yes, `user` parameters triggers SASL while only `binddn` triggers simple auth.

> ```
> [ldap2pg.manager      INFO] Querying LDAP cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=xxxx,DC=cnb...
> [ldap2pg.ldap        DEBUG] Doing: ldapsearch -x -b cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=xxxx,DC=cnb -s sub '(objectClass=groupOfNames)' member
> [ldap2pg.script   CRITICAL] Failed to query LDAP: {'info': '000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580', 'desc': 'Operations error'}.
> ```

This is not the `Invalid Credentials` error.

**Comment by bersace** [comment]
@canlar what is the server ? OpenLDAP or Active Directory ?

**Comment by canlar** [comment]
Active Directory

**Comment by bersace** [comment]
Ok, I need to check this in details. There might be some tweak for Active Directory. cf. https://blog.thomastoye.be/python-ldap-authentication-with-microsoft-active-directory-46661bebc483

**Comment by canlar** [comment]
If i not set domainname in ldapsearch command i get error. 

ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C090404, comment: AcceptSecurityContext error, data 525, v1772

IF i set user@domain.cnb when ldapsearch is sucessfull
ldapsearch -x -H ldap://xxx.cnb:389 -L -D 'user@xxx.cnb' -W -b 'CN=manager,OU=Groups,OU=IAM,OU=_DomainOperations,DC=xxxx,DC=cnb' member

**Comment by bersace** [comment]
Thanks for the point !

**Comment by bersace** [comment]
Hmm, so you have to set `user@domain.cnb` as `binddn` ? Can you put this in `LDAPBINDDN` env var or in the file. That strange because the value should be read properly from `ldaprc`.

**Comment by cbandy** [comment]
I am able to connect to the Active Directory server to which I have access.

@canlar, the `-D` argument to `ldapsearch` corresponds to the `binddn` key in `ldap2pg` YAML. Try the following:

```yaml
ldap:
  binddn: userxxx
```

**Comment by canlar** [comment]
now is working
ldap:
  binddn: userxxx

**Comment by bersace** [comment]
@canlar. Is `ldap:binddn` value the same as `ldaprc:BINDDN` ?

**Comment by canlar** [comment]
I have renamed ldaprc and configure only the yaml file.

-bash-4.2$ DEBUG=Y ldap2pg -c ldap2pg.minimal.yml
[ldap2pg.script      DEBUG] Debug mode enabled.
[ldap2pg.config      DEBUG] Processing CLI arguments.
[ldap2pg.config       INFO] Starting ldap2pg 3.3.
[ldap2pg.config      DEBUG] Trying ldap2pg.minimal.yml.
[ldap2pg.config       INFO] Using /var/lib/pgsql/ldap2pg.minimal.yml.
[ldap2pg.config      DEBUG] Read color from YAML.
[ldap2pg.config      DEBUG] Read dry from YAML.
[ldap2pg.config      DEBUG] Read verbose from DEBUG.
[ldap2pg.config      DEBUG] Read ldap:uri from YAML.
[ldap2pg.config      DEBUG] Read ldap:binddn from YAML.
[ldap2pg.config      DEBUG] Read ldap:password from YAML.
[ldap2pg.config      DEBUG] Read postgres:dsn from YAML.
[ldap2pg.config      DEBUG] Read sync_map from YAML.
[ldap2pg.config      DEBUG] Configuration loaded.
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'/etc/ldap/ldap.conf'
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'/var/lib/pgsql/ldaprc'
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'/var/lib/pgsql/.ldaprc'
[ldap2pg.ldap        DEBUG] Ignoring: [Errno 2] No such file or directory: u'ldaprc'
[ldap2pg.ldap        DEBUG] Connecting to LDAP server ldap://de.bayer.cnb:3268.
[ldap2pg.ldap        DEBUG] Trying simple bind.
[ldap2pg.script    WARNING] Running in dry mode. Postgres will be untouched.
[ldap2pg.manager      INFO] Inspecting Postgres...
......
[ldap2pg.manager     DEBUG] Generated 16 querie(s).
[ldap2pg.script       INFO] Comparison complete.
.......

-bash-4.2$ cat ldap2pg.minimal.yml
color: yes
dry: yes
ldap:
  uri: ldap://de.company.cnb:389
  binddn: mzmoc
  password: "xxxxxx"

postgres:
  dsn: postgres://username:password@hostname.de.company.cnb:5432/


sync_map:
- ldap:
    base: cn=xxxmanager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=company,DC=cnb
    filter: "(objectClass=groupOfNames)"
    attribute: member
  role:
    name_attribute: member.cn
    options: LOGIN SUPERUSER

**Comment by sgns12** [comment]
Hi
i am able to do ldapsearch against MS active directory 
ldapsearch -h ad.imsi.com -p 389 -D "cn=ldapuser=adminaccounts,dc=ad,dc=imsi,dc=com"  -w Password1 -b "ou=IFSUsers,DC=ad,DC=imsi,DC=com"  

then i try to run ldap2pg  and get below error:

ldap2pg -c /u01/Software/Postgres/ldap2pg-master/docs/ldap2pg.minimal.yml --dry --verbose
/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[ldap2pg.script       DEBUG] Debug mode enabled.
[ldap2pg.config       DEBUG] Processing CLI arguments.
[ldap2pg.config        INFO] Starting ldap2pg 4.17.
[ldap2pg.config       DEBUG] Trying /u01/Software/Postgres/ldap2pg-master/docs/ldap2pg.minimal.yml.
[ldap2pg.config        INFO] Using /u01/Software/Postgres/ldap2pg-master/docs/ldap2pg.minimal.yml.
[ldap2pg.config       DEBUG] Read dry from argv.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __connect__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __create_on_schemas__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_delete_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_insert_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_references_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_trigger_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_truncate_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_types__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __delete_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __insert_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __references_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __temporary__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __trigger_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __truncate_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_schemas__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Connecting to LDAP directory.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/etc/ldap/ldap.conf'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/usr/local/postgres/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/usr/local/postgres/.ldaprc'
[ldap2pg.ldap         DEBUG] Found rcfile /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read uri from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read BINDDN from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read BASE from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read user from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read password from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Read REFERRALS from /u01/Software/Postgres/ldap2pg-master/ldaprc.
[ldap2pg.ldap         DEBUG] Connecting to LDAP server ldap://ad.imsi.com:389.
[ldap2pg.ldap         DEBUG] Trying SASL DIGEST-MD5 auth.
[ldap2pg.ldap         DEBUG] Doing: ldapwhoami -Y DIGEST-MD5 -U imssybase -W
[ldap2pg.script       CRITI] Failed to connect to LDAP: {'desc': 'Unknown authentication method', 'errno': 2, 'info': 'SASL(-4): no mechanism available: No worthy mechs found'}


ldaprc files is
uri ldap://ad.imsi.com:389
BINDDN :cn=imssybase,ou=adminaccounts,dc=ad,dc=imsi,dc=com
user :ldapuser
password : Password1

cannot figure out why it fails.
does not look like it has to do with the MS AD/LDAP server
thank you for your help
shimshon

**Comment by bersace** [comment]
Hi @sgns12 , the ldaprc file looks odd. I don't known if the colon are valid. That should look like:

```
uri ldap://ad.imsi.com:389
BINDDN cn=imssybase,ou=adminaccounts,dc=ad,dc=imsi,dc=com
user ldapuser
password Password1
```

**Comment by sgns12** [comment]
Thank you very much for your prompt response
did 2 things 
1st - not sure if relevant - installed - yum install cyrus-sasl-md5
2nd - updated ldaprc file as you recommended
made progress and now get this error, 
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_execute_server_program'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Managing role 'espappid' NOBYPASSRLS LOGIN NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOSUPERUSER.
[ldap2pg.inspector    DEBUG] Managing role 'espreadid' NOBYPASSRLS LOGIN NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOSUPERUSER.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_monitor'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_all_stats'. Matches 'pg_*'.
[ldap2pg.manager      DEBUG] Postgres roles inspection done.
[ldap2pg.manager      DEBUG] Found role ldap_roles from YAML.
[ldap2pg.manager       INFO] Querying LDAP ou=people,dc=ldap,dc=lda... (objectClass...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -Y DIGEST-MD5 -U imssybase -W -b ou=people,dc=ldap,dc=ldap2pg,dc=docker -s sub '(objectClass=organizationalRole)' cn
[ldap2pg.script       CRITI] Failed to query LDAP: {'desc': 'Referral', 'info': 'Referral:\nldap://ldap.ldap2pg.docker/ou=people,dc=ldap,dc=ldap2pg,dc=docker'}.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.
itsrhv22113:root@/u01/Software/Postgres/ldap2pg-master/docs>


need to adjust yml i guess
thank you very much

**Comment by sgns12** [comment]
Hi
I have ldapsearch working from command line
ldapsearch -h agsos137.it.mainstr.com -p 2389 -LLL -w Password -x -D "uid=PostgresUser,ou=system,ou=users,dc=mainstreet,dc=com" -b cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=mainstreet,dc=com -s sub uniqueMember
result:
dn: cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=mainstreet,dc=com
uniqueMember: uid=e491669,ou=internal,ou=users,dc=mainstreet,dc=com

my ldaprc
uri ldap://agsos137.it.mainstr.com:2389
binddn "uid=PostgresUser,ou=system,ou=users,dc=mainstreet,dc=com"
password Password

in yml I have
base: cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=mainstreet,dc=com
filter: "cn=ssc_postgressuser_readrole"
  role:
    name: '{uniqueMember}'
    options: LOGIN


I am trying to get 
name: '{uniqueMember}' or name: '{uniqueMember.uid}' 
which would be name: e491669 from this result 
uniqueMember: uid=e491669,ou=internal,ou=users,dc=mainstreet,dc=com




when I run 
ldap2pg -c test.yml  --dry -v 
I get 0 entries from LDAP 
..........
[ldap2pg.manager       INFO] Querying LDAP cn=ssc_postgressuser_rea... cn=ssc_postg...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -b cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=statestreet,dc=com -s sub 'cn=ssc_postgressuser_readrole' uniquemember
[ldap2pg.manager      DEBUG] Got 0 entries from LDAP.
[ldap2pg.manager      DEBUG] LDAP inspection completed. Post processing
................
thank you
shimshon

**Comment by sgns12** [comment]
sorry, it should read
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -b cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=mainstreet,dc=com -s sub 'cn=ssc_postgressuser_readrole' uniquemember
[ldap2pg.manager      DEBUG] Got 0 entries from LDAP.

**Comment by bersace** [comment]
Hi @sgns12 you should open a new issue instead of polluting an old ticket.

The working ldapsearch command does not have filter while you set one in YAML. Also, the YAML you pasted looks misidented. Spaces are important in YAML. You should have something like:

``` yaml
sync_map:
- ldap:
    base: cn=ssc_postgressuser_readrole,ou=groups,ou=users,dc=mainstreet,dc=com
    scope: sub
    filter: '(cn=ssc_postgresuser…)'
  role:
    name: '{uniqueMember}'
    options: LOGIN
```

**Comment by sgns12** [comment]
Thank you for you response and realize I have to open a new issue and not to resue old one.
sorry.
found my problem.
for some reason ldap2pg does not pick up ldaprc file that I have in the same directory for this specific ldap. 
for 2 other ldaps ldaprc files in their own directories  work fine.
defined unix variables like LDAPBINDDN and LDAPURI, LDAPPORT and LDAPPASSWORD and it runs fine.
thank you and my apologies for reusing the thread

**Comment by bersace** [comment]
Hi @sgns12 , hmm there may be a bug in ldap2pg when loading ldaprc. Can you upload debug logs in a new issue ?
