### ISSUE TITLE
Can't define sasl_mech in /etc/ldap2pg.yml

### ISSUE THREAD

**Issue by micahthepenguin** [dalibo/ldap2pg#354]
To enable Kerberos for authenticating LDAP queries, it would be convenient to set `sasl_mech: GSSAPI` in `/etc/ldap2pg.yml` where other LDAP parameters can be set, but I get `Unknown config entry: ldap:sasl_mech.` in the verbose output when attempting to set it there.

Can `sasl_mech` be added to the known config parameters, or was it left out intentionally?

I am able to work around this by adding `SASL_MECH GSSAPI` to `~postgres/.ldaprc`, or alternatively by setting the `LDAP_SASL_MECH` environment variable to `GSSAPI`.

**Comment by bersace** [comment]
Hi @micahthepenguin , thanks for the report.

I suggest to avoid at most connexion configuration in ldap2pg.yml. It is not read by ldap utils, and requires extra code pretty dumb that need to be synchronized with libldap.

I suggest to ship a ldaprc file along ldap2pg.yml. Your workaround is actually the expected behaviour.

**Comment by micahthepenguin** [comment]
Understood.  Thanks.
