### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by tstepien0** [dalibo/ldap2pg#660]
In the documentation regarding [built-in privileges](https://ldap2pg.readthedocs.io/en/latest/builtins/) in section "Profiles reference", both "usage_on_schemas" and "usage_on_schema" appear. Only the first parameter is correct; the second one can be misleading and doesn't work.

**Comment by tomgachet** [comment]
You're right @tstepien0 !
The error is actually in the  [Profile __all_on_schemas__](https://ldap2pg.readthedocs.io/en/latest/builtins/#all-on-schemas) section. 
The privilege `__usage_on_schema__` must be `__usage_on_schemas__` to be functional!

**Comment by bersace** [comment]
Hi, thanks for the report.

Actually, this was a bug in configuration defaults fixed in 643f1387a5d60b469df1184ebebd7fdb8fc18ed0 . Which mean 6.1 has a bug in default configuration. `__all_on_schemas__` does not effectively include `__usage_on_schemas__`.

I regenerated documentation.

Please keep the issue open so I track a final task on this issue : prevent regression by controlling consistency of default configuration.

Thanks @tomgachet for the head-up.

Regards,

**Comment by tomgachet** [comment]
Thanks @bersace  , it's a pleasure to contribute modestly to ldap2pg!

**Comment by bersace** [comment]
Fixed in 6.2
